#pragma checksum "MovieView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "A80A1A695372C4EBAB2DE0D8D3C52BFD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MovieDatabase;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace MovieDatabase {
    
    
    /// <summary>
    /// MovieView
    /// </summary>
    public partial class MovieView : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FileMenu;
        
        #line default
        #line hidden
        
        
        #line 14 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FileNew;
        
        #line default
        #line hidden
        
        
        #line 15 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FileLoad;
        
        #line default
        #line hidden
        
        
        #line 16 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FileSave;
        
        #line default
        #line hidden
        
        
        #line 18 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FileExit;
        
        #line default
        #line hidden
        
        
        #line 21 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EditMenu;
        
        #line default
        #line hidden
        
        
        #line 22 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EditCreate;
        
        #line default
        #line hidden
        
        
        #line 23 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EditEdit;
        
        #line default
        #line hidden
        
        
        #line 25 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EditDelete;
        
        #line default
        #line hidden
        
        
        #line 28 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ViewMenu;
        
        #line default
        #line hidden
        
        
        #line 29 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ViewTitle;
        
        #line default
        #line hidden
        
        
        #line 30 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ViewYear;
        
        #line default
        #line hidden
        
        
        #line 31 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ViewDUration;
        
        #line default
        #line hidden
        
        
        #line 34 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem HelpMenu;
        
        #line default
        #line hidden
        
        
        #line 35 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ViewAbout;
        
        #line default
        #line hidden
        
        
        #line 50 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FirstB;
        
        #line default
        #line hidden
        
        
        #line 51 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NextB;
        
        #line default
        #line hidden
        
        
        #line 52 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PrevB;
        
        #line default
        #line hidden
        
        
        #line 53 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LastB;
        
        #line default
        #line hidden
        
        
        #line 54 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelB;
        
        #line default
        #line hidden
        
        
        #line 55 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveB;
        
        #line default
        #line hidden
        
        
        #line 78 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TitleText;
        
        #line default
        #line hidden
        
        
        #line 100 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DurationText;
        
        #line default
        #line hidden
        
        
        #line 101 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox YearText;
        
        #line default
        #line hidden
        
        
        #line 118 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BudgetText;
        
        #line default
        #line hidden
        
        
        #line 119 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MovieDatabase.RatingControl RatingControl;
        
        #line default
        #line hidden
        
        
        #line 133 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DirectorText;
        
        #line default
        #line hidden
        
        
        #line 137 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox GenreCheck;
        
        #line default
        #line hidden
        
        
        #line 140 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Comedy;
        
        #line default
        #line hidden
        
        
        #line 141 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Romance;
        
        #line default
        #line hidden
        
        
        #line 142 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Action;
        
        #line default
        #line hidden
        
        
        #line 143 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Thriller;
        
        #line default
        #line hidden
        
        
        #line 144 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Family;
        
        #line default
        #line hidden
        
        
        #line 145 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Horor;
        
        #line default
        #line hidden
        
        
        #line 146 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Western;
        
        #line default
        #line hidden
        
        
        #line 147 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SciFi;
        
        #line default
        #line hidden
        
        
        #line 148 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox War;
        
        #line default
        #line hidden
        
        
        #line 165 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CastText;
        
        #line default
        #line hidden
        
        
        #line 187 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Image;
        
        #line default
        #line hidden
        
        
        #line 188 "MovieView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox URLText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/MovieDatabase;component/movieview.xaml", System.UriKind.Relative);
            
            #line 1 "MovieView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.FileMenu = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 2:
            this.FileNew = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 3:
            this.FileLoad = ((System.Windows.Controls.MenuItem)(target));
            
            #line 15 "MovieView.xaml"
            this.FileLoad.Click += new System.Windows.RoutedEventHandler(this.FileLoad_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.FileSave = ((System.Windows.Controls.MenuItem)(target));
            
            #line 16 "MovieView.xaml"
            this.FileSave.Click += new System.Windows.RoutedEventHandler(this.FileSave_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.FileExit = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 6:
            this.EditMenu = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 7:
            this.EditCreate = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 8:
            this.EditEdit = ((System.Windows.Controls.MenuItem)(target));
            
            #line 23 "MovieView.xaml"
            this.EditEdit.Click += new System.Windows.RoutedEventHandler(this.EditMenu_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.EditDelete = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 10:
            this.ViewMenu = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 11:
            this.ViewTitle = ((System.Windows.Controls.MenuItem)(target));
            
            #line 29 "MovieView.xaml"
            this.ViewTitle.Click += new System.Windows.RoutedEventHandler(this.ViewTitle_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ViewYear = ((System.Windows.Controls.MenuItem)(target));
            
            #line 30 "MovieView.xaml"
            this.ViewYear.Click += new System.Windows.RoutedEventHandler(this.ViewYear_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ViewDUration = ((System.Windows.Controls.MenuItem)(target));
            
            #line 31 "MovieView.xaml"
            this.ViewDUration.Click += new System.Windows.RoutedEventHandler(this.ViewDUration_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.HelpMenu = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 15:
            this.ViewAbout = ((System.Windows.Controls.MenuItem)(target));
            
            #line 35 "MovieView.xaml"
            this.ViewAbout.Click += new System.Windows.RoutedEventHandler(this.ViewAbout_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.FirstB = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.NextB = ((System.Windows.Controls.Button)(target));
            
            #line 51 "MovieView.xaml"
            this.NextB.Click += new System.Windows.RoutedEventHandler(this.NextB_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.PrevB = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.LastB = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.CancelB = ((System.Windows.Controls.Button)(target));
            
            #line 54 "MovieView.xaml"
            this.CancelB.Click += new System.Windows.RoutedEventHandler(this.CancelB_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.SaveB = ((System.Windows.Controls.Button)(target));
            
            #line 55 "MovieView.xaml"
            this.SaveB.Click += new System.Windows.RoutedEventHandler(this.SaveB_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.TitleText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.DurationText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.YearText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 25:
            this.BudgetText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            this.RatingControl = ((MovieDatabase.RatingControl)(target));
            return;
            case 27:
            this.DirectorText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.GenreCheck = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 29:
            this.Comedy = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 30:
            this.Romance = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 31:
            this.Action = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 32:
            this.Thriller = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 33:
            this.Family = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 34:
            this.Horor = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 35:
            this.Western = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 36:
            this.SciFi = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 37:
            this.War = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 38:
            this.CastText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.Image = ((System.Windows.Controls.Image)(target));
            return;
            case 40:
            this.URLText = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

